### ISSUE TITLE
Can't install via panda.

### ISSUE THREAD

**Issue by coke** [ShimmerFairy/grammar-parsefail#1]
Can't install via panda.

Trying to debug your SUPERNOVA issue, I attempted to install this module to test. It failed:

```
$ panda install Grammar::Parsefail
==> Fetching Grammar::Parsefail
Please remove leading 'v' from perl version in Grammar::Parsefail's meta info.
Grammar::Parsefail requires Perl version 6.0.0. Cannot continue.
```

I believe that the correct version required here is "6.c" not "v6.0.0"

**Comment by ShimmerFairy** [comment]
Fixed, though I 'm surprised rakudo/perl6 has no handling in place for the old name of 6.c, from back before we decided on the holiday naming.
